apiVersion: v1
kind: Service
matadata:
  name: nginx-service
spec:
  type: LoadBalancer
  ports: 
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx-deployment  